[[ -f ~/.config/X11/xresources ]] && xrdb -merge -I$HOME ~/.config/X11/xresources &
clipmenud &
sxhkd &
(sleep 10s && dunst) &
calcurse --daemon &

autorandr -c &
xsetroot -cursor_name left_ptr &
toggleredshift &
togglelocker &

emacs --daemon &

nextcloud &

#setxkbmap -option caps:swapescape &
setxkbmap -option ctrl:nocaps &
picom &
unclutter &

dwmblocks &
while :; do
	ssh-agent dwm
done
