[[ -f ~/.config/X11/xresources ]] && xrdb -merge -I$HOME ~/.config/X11/xresources &
clipmenud &
sxhkd &
dunst &
(mpd && mpc repeat on && mpc mpc random on) &
calcurse --daemon &

makescheme
xsetroot -cursor_name left_ptr &
toggleredshift &
togglelocker &

nextcloud &

setxkbmap -option caps:swapescape &
autorandr -c &
picom &
unclutter &

dwmblocks
while :; do
	ssh-agent dwm
done
