picom &
setbg &                                                             #eigenes script, setzt hintergrund
togglelocker &                                                      #eigenes script, aktiviert den locker
unclutter &                                                         #versteckt den cursor nach 5 sek
xsetroot -cursor_name left_ptr &                                    #setzt den cursor
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources &
dunst &                                                             #daemon fuer notifications
sxhkd &                                                             #daemon fuer hotkeys
autorandr -c &                                                      #setzt die bildschirme so, dass sie mir passen (-c lädt das erste passende profil)
clipmenud &                                                         #clipboardmanager
blueman-applet &


nextcloud &
#keepassxc &
#bitwarden &
startthunderbird &
#telegram-desktop &
#whatsapp-nativefier &


setxkbmap -option caps:swapescape &                                 #tauscht capslock und esc

#exec i3                                                            #startet i3
dwmblocks &                                                         #statusbar für dwm
exec dwm                                                            #startet dwm
